### ISSUE TITLE
System Out of Memory Exception on SetupEnviornment (LZ4 Decompression)

### ISSUE THREAD

**Issue by BenMagyar** [poulfoged/Elasticsearch-Inside#1]
Attempted to get this going on a project I was working on but was unable to. I was able to run the tests against the actual Elasticsearch-Inside project without issue, which is surprising. 

I did a quick test and switched from the LZ4 file to a ZIP and I was able to run the tests. Startup time increased about 3 seconds, but I might just roll with that for now. 

So it might not really have anything to do with the library and instead with LZ4 decompression, but it might be a good idea to look into an alternative. 

```
Result StackTrace:	
at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode)
   at ElasticsearchInside.Elasticsearch.ExtractEmbeddedLz4Stream(String name, DirectoryInfo destination)
   at ElasticsearchInside.Elasticsearch.<SetupEnvironment>b__3()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
 

Result Message:	
Test method w exception: 
System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
```

**Comment by poulfoged** [comment]
Looks like ZipArchive allocates a new MemoryStream and copies everything to it if it cannot seek on the the source stream (the LZ4 output). Your case probably worked because no new allocations was necessary. 

I'll look for a better solution.

**Comment by poulfoged** [comment]
Ok, I've rolled my own archive-format instead of ziparchive, it does not require seek on the source stream so it can read the lz4 stream directly. 

Since I have not been able to recreate your error it would be awesome if you could try it out from the branch [avoid-ziparchive-memorystream](https://github.com/poulfoged/Elasticsearch-Inside/tree/avoid-ziparchive-memorystream) and let me know how it goes.

**Comment by BenMagyar** [comment]
Just gave it a try and it looks like the solution worked, thank you!
